//package com.example.recipes.model;
//
//import org.springframework.data.annotation.Id;
////
////public record Recipe(@Id Integer id , String name, String description, Integer timeRequired, String mealType) {
////
////}
//
//import com.fasterxml.jackson.annotation.JsonProperty;
//
//public record Recipe(@Id Integer id, @JsonProperty("name") String name, @JsonProperty("description") String description, @JsonProperty("timeRequired") Integer timeRequired, @JsonProperty("mealType") String mealType) {
//    // Constructor, getters, and setters are automatically generated by the record feature.
//}
//


package com.example.recipes.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Recipe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String name;
    private String description;
    private int timeRequired;
    private String mealType;

    // Constructors
    public Recipe() {}

    public Recipe(String name, String description, int timeRequired, String mealType) {
        this.name = name;
        this.description = description;
        this.timeRequired = timeRequired;
        this.mealType = mealType;
    }

    // Getters and setters
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getTimeRequired() {
        return timeRequired;
    }

    public void setTimeRequired(int timeRequired) {
        this.timeRequired = timeRequired;
    }

    public String getMealType() {
        return mealType;
    }

    public void setMealType(String mealType) {
        this.mealType = mealType;
    }
}
